### ISSUE TITLE
Missing Trigger in triggerNames branch

### ISSUE THREAD

**Issue by drberry85** [UHH2/UHH2#140] opened 2015-08-04 21:06 UTC
Hey All,

When running on multiple files, if the first file never fires a certain trigger then that trigger is missing from the triggerNames branch even if a later file does fire that trigger. So this means if you run over many small files you can occasionally drop a trigger, which leads to an exception:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Inconsistent trigger information: trigger names for current run have size 415, but trigger results for current event have size 416
```
An ugly patch solution is that each time a new TChain is added, you need to check the triggerNames size and add any missing Names. A better solution is just to store the list of triggers that fires in each event and the auto compression of root will keep the file size small.

Doug

**Comment by emanueleusai** [comment] 2015-08-04 21:19
I got this same error and I actually thought this was due to a bug in 
the PFHT800 emulator. The bug is fixed in the ntuplewriter now 
(https://github.com/UHH2/UHH2/pull/129) and in some rare cases this 
happens in the current ntuples.
I observed this in a bunch of events in low pt hat bins of the QCD samples.
To fix this you could do the following:
change the block at line 105 of core/src/Event.cxx with something like:

    if(triggerNames_currentrun.size() != triggerResults->size()){
        stringstream ss;
        ss << "Inconsistent trigger information: trigger names for 
current run have size " << triggerNames_currentrun.size() << ", but 
trigger results for current event have size " << triggerResults->size()
           << endl;
           if (triggerNames_currentrun.size()-triggerResults->size() != 1)
        throw runtime_error(ss.str());
            else triggerResults->push_back(0);
    }

(that loosens up the trigger sanity check)

I didn't want to commit this change because I guess we'll be running a 
new ntuple production soon with updated object reconstruction (MET 
filters, etc).
Let me know if you have doubts or a better solution.

Cheers,
Emanuele


Il 04/08/15 23:06, Doug Berry ha scritto:

**Comment by peiffer** [comment] 2015-08-11 08:48
Hi Emanuele, 

could you please confirm that this bug is fixed now? Since I added the MET filters as trigger bits at the end of the trigger list, it would be dangerous if the trigger bits are shifted by 1 with resepct to the trigger names.

When running small test jobs, I did not observe any discrepancy in the size of the trigger lists. So I guess, the problem is fixed with your pull request #129.

Cheers,

Thomas

**Comment by emanueleusai** [comment] 2015-08-11 15:29
Hi Thomas,

This feature hasn't been extensively tested. One should rerun one of the 
small pthat qcd samples that was causing the problem and make sure that 
the problem doesn't appear again (without the dirty hack suppressing the 
errors).
Unfortunately I can't do it now because I'm am at a conference. But I 
can provide gridcontrol configurations...

Which sample did you run? this problems didn't appear at all in Z' 
signal samples, top samples, QCD high pthat, etc. (and this is the 
reason I didn't notice it while testing the feature)
To be really sure one would have to fully rerun a 15to30 or 30to50 or 
50to80.

We could start the new production with these samples, if we see problems 
we just wasted a few M of events of computational time, if the PR fully 
solves the problem (I'm rather confident of this), we can move on to the 
more important samples (ttbar, signals, etc)

Cheers,
Emanuele

Il 11/08/15 03:48, Thomas Peiffer ha scritto:

**Comment by peiffer** [comment] 2015-08-11 15:41
Hi Emanuele,

I was only testing the single muon data and one Z' sample.

The QCD samples 15to30 and 50to80 are at DESY. I have a working setup to run at DESY, so I will start producing them. If the problem disappears we can start the full production.

The 30to50 sample has been invalidated in DAS. There is only a recodebug sample available at T2_FR_CCIN2P3.

Cheers,

Thomas

**Comment by emanueleusai** [comment] 2015-08-11 16:38
Hi Thomas,

Thank you very much for taking care of this.
Yes the whole dataset is at DESY, so this should be fast (normally it took an afternoon to run over a couple of QCD samples)
I didn't know the 30to50 was invalidated...

Cheers.
Emanuele

**Comment by peiffer** [comment] 2015-08-12 07:28
Hi,

I have processed the two QCD samples 15to30 and 50to80. When running the trigger selection with the triggers HLT_Mu50 or HLT_PFHT800Emu, I do not observe any issue on both samples. Seems that the bug is fixed and this issue can be closed.

Cheers,
Thomas

**Closed by peiffer** 2015-08-12 07:28 UTC
